services:
  app_service_a:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:VNO78RgpAR/bPAo+n1hAWXqrrbDey9+V3LRi/sQSBVU=
      - DB_CONNECTION=sqlite
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
      - IAE_ALLOWED_KEY=102022400039
    networks:
      - smart_parking_net

networks:
  smart_parking_net:
    driver: bridge
